project:
  title: mb-article
  type: website
  execute-dir: file
  output-dir: docs
  preview:
    port: 5555

highlight-style: tango 

website:
  title: mb-article
  favicon: logo.png
  image: logo.png
  twitter-card: false
  description: Quarto extension
  open-graph: true
  site-url: https://mbacou.github.io/mb-article
  repo-url: https://github.com/mbacou/mb-article
  repo-branch: main
  repo-actions: none
  back-to-top-navigation: false
  page-navigation: true
  bread-crumbs: true

  search:
    show-item-context: true

  navbar: false
  sidebar:
    style: floating
    border: false
    search: false
    alignment: right

