project:
  title: mb-article
  type: website
  execute-dir: file
  output-dir: docs
  preview:
    port: 5555

highlight-style: tango 

website:
  title: mb-article
  favicon: logo.png
  image: logo.png
  twitter-card: false
  description: Quarto extension
  open-graph: true
  site-url: https://mbacou.github.io/mb-article
  repo-url: https://github.com/mbacou/mb-article
  repo-branch: main
  repo-actions: [edit, issue]
  back-to-top-navigation: false
  page-navigation: true
  bread-crumbs: true
  sidebar:
    background: transparent
    logo: logo.png
    style: floating
    search: false
    footer: |
      <strong>Mel B. Labs</strong> -- a personal blog about statistics
      and spatial econometrics. BACOU, Melanie © 2024 under 
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en">
      CC BY-NC 4.0</a>
  other-links: 
    - href: ./
      icon: arrow-up-square-fill
      text: Back to top
    - href: "#quarto-appendix"
      icon: arrow-up-square-fill
      text: Appendix    


