project:
  title: mb-article
  type: website
  execute-dir: file
  output-dir: docs
  preview:
    port: 5555

website:
  title: "mb-article - Quarto Format"
  favicon: assets/favicon.svg
  image: assets/logo.svg
  description: mb-article - Custom Quarto Format
  site-url: https://mbacou.github.io/mb-article
  repo-url: https://github.com/mbacou/mb-article
  repo-actions: [edit, issue]
  back-to-top-navigation: false
  page-navigation: false
  bread-crumbs: false
  search:
    type: overlay
    show-item-context: true  

highlight-style: a11y-light
bibliography: references.bib

format:
  mb-article-html:
    logo: assets/logo.svg
    logo-href: /
    license: CC BY-NC 4.0
    copyright: © 2026, Mel B. Labs.
    header:
      palette: true
      left:
        - text: Link 1
          icon: link
          href: index.qmd
        - text: Link 2
          icon: link
          href: index.qmd
        - text: Link 3
          icon: link
          href: index.qmd            
      right: 
        - icon: github
          href: https://github.com/mbacou/mb-article
        - icon: telegram
          href: https://t.me/mbacou
        - icon: linkedin
          href: https://linkedin.com/in/mbacou
        - icon: youtube
          href: https://youtube.com/\@mbacou/playlists

