project:
  title: mb-article
  type: website
  execute-dir: file
  output-dir: docs
  preview:
    port: 5555

website:
  title: "mb-article - Quarto Format"
  favicon: favicon.svg
  image: logo.svg
  description: mb-article - Custom Quarto Format
  site-url: https://mbacou.github.io/mb-article
  repo-url: https://github.com/mbacou/mb-article
  repo-actions: [edit, issue]
  search: true 
  back-to-top-navigation: false
  page-navigation: false
  bread-crumbs: false

highlight-style: a11y-light
execute: 
  results: hold

format:
  mb-article-html:
    author:
      - name: BACOU, Melanie
        linkedin: mbacou 
        email: author-1@mail.com
        orcid: 0000-0003-1810-6820
        affiliation: mbacou.com

    status: DRAFT waiting for review

    logo: logo.svg
    logo-href: /
    title-block-banner: url(banner.svg)  
    license: CC BY-NC 4.0
    copyright: © Mel B. Labs - a personal blog about statistics and spatial econometrics.

    header:
      palette: true
      left:
        - text: Menu 1
          icon: link
          href: index.qmd
        - text: Menu 2
          icon: link
          href: index.qmd       
      right: 
        - icon: github
          href: https://github.com/mbacou/mb-article
        - icon: telegram
          href: https://t.me/mbacou
        - icon: linkedin
          href: https://linkedin.com/in/mbacou
        - icon: youtube
          href: https://youtube.com/\@mbacou/playlists

